import React from 'react';
import {
  Wallet,
  Coins,
  TrendingUp,
  TrendingDown,
  ArrowUpRight,
  ArrowDownRight,
  Layers,
  CheckCircle2,
  PieChart,
  Percent,
  Calculator,
  Info,
} from 'lucide-react';
import { formatPKR, formatPercent, formatNumber } from '../utils/formatters';
import { PortfolioKPIs } from '../types';

interface TopKPISectionProps {
  kpis: PortfolioKPIs;
  darkMode: boolean;
}

export const TopKPISection: React.FC<TopKPISectionProps> = ({ kpis, darkMode }) => {
  const kpiItems = [
    {
      id: 'kpi-portfolio-value',
      label: 'Total Portfolio Value',
      value: formatPKR(kpis.portfolioValue),
      subtext: 'Cash + Market Value of Positions',
      tooltip: 'Formula: Available Cash Balance + Sum(Quantity × Latest PSX Market Price). Represents total liquidation equity.',
      isPositive: null,
      icon: Wallet,
      highlight: true,
    },
    {
      id: 'kpi-available-cash',
      label: 'Available Cash',
      value: formatPKR(kpis.availableCash),
      subtext: 'Deployable Liquidity',
      tooltip: 'Formula: Opening Capital + Total Deposits - Total Withdrawals + Realized P&L - Cost deployed in active positions.',
      isPositive: null,
      icon: Coins,
    },
    {
      id: 'kpi-invested-capital',
      label: 'Invested Capital',
      value: formatPKR(kpis.investedCapital),
      subtext: 'De-facto Cost Basis',
      tooltip: 'Formula: Sum of entry cost basis (price × quantity + trade entry fees) currently tied up in open positions.',
      isPositive: null,
      icon: Layers,
    },
    {
      id: 'kpi-net-capital',
      label: 'Net Capital',
      value: formatPKR(kpis.netCapital),
      subtext: `Deposits ${formatPKR(kpis.totalDeposits, { compact: true })} - Withdr ${formatPKR(kpis.totalWithdrawals, { compact: true })}`,
      tooltip: 'Formula: Total Deposits − Total Withdrawals. Reflects net external capital funded into the account.',
      isPositive: null,
      icon: Calculator,
    },
    {
      id: 'kpi-unrealized-pnl',
      label: 'Unrealized P&L',
      value: formatPKR(kpis.unrealizedPnL, { showSign: true }),
      subtext: 'Open Positions Float',
      tooltip: 'Formula: Current Market Value of Open Positions − Cost Basis. Floating profit or loss.',
      isPositive: kpis.unrealizedPnL >= 0,
      icon: kpis.unrealizedPnL >= 0 ? TrendingUp : TrendingDown,
    },
    {
      id: 'kpi-realized-pnl',
      label: 'Realized P&L',
      value: formatPKR(kpis.realizedPnL, { showSign: true }),
      subtext: 'Closed Positions (Net of Fees)',
      tooltip: 'Formula: Sum of net P&L from all closed trades and partial scales after deduction of broker commissions and taxes.',
      isPositive: kpis.realizedPnL >= 0,
      icon: CheckCircle2,
    },
    {
      id: 'kpi-total-pnl',
      label: 'Total P&L',
      value: formatPKR(kpis.totalPnL, { showSign: true }),
      subtext: `Return: ${formatPercent(kpis.returnPercent)}`,
      tooltip: 'Formula: Realized P&L + Unrealized P&L. Total trading alpha generated by strategy.',
      isPositive: kpis.totalPnL >= 0,
      icon: PieChart,
      highlight: true,
    },
    {
      id: 'kpi-portfolio-return',
      label: 'Return %',
      value: formatPercent(kpis.returnPercent),
      subtext: 'Trading P&L / Capital Base',
      tooltip: 'Formula: Total Trading P&L ÷ (Opening Capital + Net Capital) × 100.',
      isPositive: kpis.returnPercent >= 0,
      icon: Percent,
    },
    {
      id: 'kpi-today-pnl',
      label: "Today's P&L",
      value: formatPKR(kpis.todayPnL, { showSign: true }),
      subtext: formatPercent(kpis.todayPnLPercent),
      tooltip: "Formula: Today's unrealized mark-to-market change of open positions + today's realized closed trade P&L.",
      isPositive: kpis.todayPnL >= 0,
      icon: kpis.todayPnL >= 0 ? ArrowUpRight : ArrowDownRight,
    },
    {
      id: 'kpi-open-positions',
      label: 'Open Positions',
      value: formatNumber(kpis.openPositionsCount),
      subtext: 'Active Symbols',
      tooltip: 'Number of discrete stock positions currently active in the portfolio.',
      isPositive: null,
      icon: Layers,
    },
    {
      id: 'kpi-closed-trades',
      label: 'Closed Trades',
      value: formatNumber(kpis.closedTradesCount),
      subtext: 'Completed Samples',
      tooltip: 'Total count of closed trades and partial profit/loss realizations.',
      isPositive: null,
      icon: CheckCircle2,
    },
    {
      id: 'kpi-win-rate',
      label: 'Win Rate',
      value: formatPercent(kpis.winRate, { showSign: false }),
      subtext: 'Closed Trade Hit Ratio',
      tooltip: 'Formula: (Winning Closed Trades ÷ Total Closed Trades) × 100.',
      isPositive: kpis.winRate >= 50,
      icon: Percent,
    },
    {
      id: 'kpi-profit-factor',
      label: 'Profit Factor',
      value: kpis.profitFactor >= 99 ? '99.9+' : kpis.profitFactor.toFixed(2),
      subtext: 'Gross Profit / Gross Loss',
      tooltip: 'Formula: Gross Profit ÷ Gross Loss. Measures overall system profitability edge (> 1.5 is institutional grade).',
      isPositive: kpis.profitFactor >= 1.5,
      icon: Calculator,
    },
    {
      id: 'kpi-total-deposits',
      label: 'Total Deposits',
      value: formatPKR(kpis.totalDeposits),
      subtext: 'Capital Injections',
      tooltip: 'Cumulative sum of all cash deposits into the brokerage CDS account.',
      isPositive: null,
      icon: ArrowUpRight,
    },
    {
      id: 'kpi-total-withdrawals',
      label: 'Total Withdrawals',
      value: formatPKR(kpis.totalWithdrawals),
      subtext: 'Capital Removals',
      tooltip: 'Cumulative sum of all cash distributions or withdrawals taken from the trading account.',
      isPositive: null,
      icon: ArrowDownRight,
    },
  ];

  return (
    <section className="px-4 py-2.5 border-b border-[#1E2229] bg-[#0E1116] select-none">
      <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 xl:grid-cols-8 gap-2">
        {kpiItems.map((item) => {
          return (
            <div
              key={item.id}
              id={item.id}
              title={item.tooltip}
              className={`p-2.5 rounded border transition-colors relative group cursor-help ${
                item.highlight
                  ? 'bg-[#161B22] border-blue-500/40 shadow-xs'
                  : 'bg-[#161B22] border-[#1E2229] hover:border-[#2D333D]'
              }`}
            >
              <div className="flex items-center justify-between gap-1 mb-1">
                <span className="text-[10px] uppercase font-mono tracking-wider text-gray-500 font-medium truncate">
                  {item.label}
                </span>
                <Info className="w-3 h-3 text-gray-500 opacity-0 group-hover:opacity-100 transition-opacity shrink-0" />
              </div>

              <div className="flex items-baseline justify-between gap-1">
                <span
                  className={`text-sm sm:text-base font-bold font-mono tracking-tight truncate ${
                    item.isPositive === true
                      ? 'text-emerald-500'
                      : item.isPositive === false
                      ? 'text-rose-500'
                      : 'text-white'
                  }`}
                >
                  {item.value}
                </span>
              </div>

              <div className="text-[10px] font-mono text-gray-500 truncate mt-0.5">
                {item.subtext}
              </div>
            </div>
          );
        })}
      </div>
    </section>
  );
};
